# Generated by Django 4.0.1 on 2022-01-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('day', models.IntegerField()),
                ('slot_number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='timetable.section')),
                ('tableEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='timetable.timetable')),
            ],
        ),
    ]
